# General
alias ..="cd .."
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
alias size="stat -f%z"
alias serve="python -m SimpleHTTPServer"
alias weather="curl wttr.in"
alias clock="tty-clock -b -s -c -C 2"
alias diff="colordiff"

# Mnemonic
# [B]ash
alias brc="vi ~/.bash_profile"
alias brcs="source ~/.bash_profile"

# [E]macs
alias ec="emacsclient -c -n"
alias ed="emacs --daemon"
alias ekd="emacsclient -e '(kill-emacs)'"

# [L]ist
alias ll="ls -la -Gfh"
alias ls="ls -Gfh"

# [V]im
alias vi="nvim"
alias vrc="vi ~/.vimrc"

# [R]anger
alias r="ranger"
