# General
alias ..="cd .."
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
alias size="stat -f%z"
alias serve="python -m SimpleHTTPServer"
alias weather="curl wttr.in"
alias clock="tty-clock -b -s -c -C 2"
alias diff="colordiff"

# Mnemonic
# [B]ash
alias brc="vi ~/.bash_profile"
alias brcs="source ~/.bash_profile"

# [E]macs
alias ec="emacsclient -c -n"
alias ed="emacs --daemon"
alias ekd="emacsclient -e '(kill-emacs)'"

# [G]it
alias ga="git add -p"
alias gall="git add --all"
alias gm="git merge"
alias gdf="git diff"
alias gls="git branch -l"
alias gco="git checkout"
alias gcp="git cherry-pick"
alias gup="git fetch; git pull"
alias gc="git commit -S"
alias gca="git commit -S --amend"
alias gcs="git commit -S --amend --no-edit"
alias gcm="git commit -S -m"
alias gpo="git push origin"
alias gcl="git clone"
alias gst="git status"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias grb="git rebase"
alias grbi="git rebase -i"
alias gpr="git pull-request"
alias gr="git rebase"
alias grc="git rebase --continue"
alias gbd="git branch -D"

# [L]ist
alias ll="ls -la -Gfh"
alias ls="ls -Gfh"

# [V]im
alias vi="nvim"
alias vrc="vi ~/.vimrc"

# [R]anger
alias r="ranger"
